work_dir: '/home/fesian/AI_workspace/research/public_skelgcn/work_dirs/train_gn/'

model_args:
  num_action: 60
  num_person: 2
  num_joint: 25
  num_frame: 300
  num_channel: 3
  dropout: 0.2
  temp_mode: 'None'

feeder: feeder.ntu_feeder.NTU_Feeder
model: network.dgl_stgcn.STGCN

train_feeder_args:
  x_mode: 'xsub'
  t_mode: 'train'
  # valid_length: 100

test_feeder_args:
  x_mode: 'xsub'
  t_mode: 'test'
  # valid_length: 240

phase: 'train'
num_workers: 5
print_log: True
device: 0
batch_size: 8
weight_decay: 0.00
base_lr: 0.001
step: [10, 50]
optimizer: 'Adam'
nesterov: True

log_interval: 200
save_interval: 2
eval_interval: 2


# force_run: True # run the inference no matter the weights loaded or not
# weights: '/home/fesian/AI_workspace/research/public_skelgcn/work_dirs/dgl_ntu_1/epoch46_model.pt'