work_dir: '/home/fesian/AI_workspace/research/public_skelgcn/work_dirs/dgl_ntu_1/'

model_args:
  num_person: 2
  num_joint: 25
  num_frame: 300
  num_channel: 3
  dropout: 0.5

feeder: feeder.ntu_feeder_fast.NTU_Feeder
model: network.dgl_stgcn.STGCN

train_feeder_args:
  x_mode: 'xsub'
  t_mode: 'train'
  # valid_length: None

test_feeder_args:
  x_mode: 'xsub'
  t_mode: 'test'
  # valid_length: None

num_workers: 5
print_log: True
device: 1
batch_size: 8
weight_decay: 0.001
base_lr: 0.01
step: [10, 50]
optimizer: 'SGD'
nesterov: True

log_interval: 100
eval_interval: 2